---
name: Publish Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"

      # - name: Install dependencies
      #   run: poetry install --no-interaction

      - name: Build source and wheel archives
        run: poetry build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@6a02ab807dd289aa281becac7152f29621389dd1 # v1.2.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
